Home work №1

In [5]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.arange(1, 11, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
m = np.random.randint(1, 11, size=(5, 5))
print(m)

[[ 5  1  9  1  7]
 [ 1  3  5  1  8]
 [ 8  7  4  1 10]
 [ 1  3  7  7  9]
 [ 8  3  5  8  8]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [15]:
m = np.random.rand(4, 4)
print(m)

[[0.83696288 0.90910371 0.99338091 0.91566028]
 [0.4978499  0.96716635 0.69175927 0.66580241]
 [0.68516608 0.29693749 0.2825515  0.66781259]
 [0.84827992 0.25766273 0.96670551 0.23290665]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
a = np.random.randint(1, 11, size=(5))
b = np.random.randint(1, 11, size=(5))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)

[ 1  7  8  5 10]
[5 6 8 9 7]
[ 6 13 16 14 17]
[-4  1  0 -4  3]
[ 5 42 64 45 70]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
a = np.random.random(7)
b = np.random.random(7)
print(a)
print(b)
print(np.dot(a,b))

[0.22066563 0.23364003 0.8404032  0.9877508  0.38862825 0.95423511
 0.38594902]
[0.01795083 0.64968764 0.33215184 0.9611098  0.91585901 0.7058385
 0.61291974]
2.6502529588735904


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(a)
print(b)
print(np.dot(a,b))

[[5 6]
 [7 7]]
[[10  9  3]
 [10  5  3]]
[[110  75  33]
 [140  98  42]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
a = np.random.randint(1, 11, size=(3, 3))
a_inv = np.linalg.inv(a)
print(a)
print(a_inv)

[[5 9 8]
 [2 5 9]
 [9 5 7]]
[[-0.03663004 -0.08424908  0.15018315]
 [ 0.24542125 -0.13553114 -0.10622711]
 [-0.12820513  0.20512821  0.02564103]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [14]:
a = np.random.rand(4, 4)
b = a.T
print(a)
print(b)

[[0.87423553 0.74190342 0.54842808 0.06475283]
 [0.5594364  0.5776671  0.00830411 0.0668152 ]
 [0.30182401 0.13694232 0.62221696 0.23010053]
 [0.64472098 0.38743249 0.3153407  0.77594973]]
[[0.87423553 0.5594364  0.30182401 0.64472098]
 [0.74190342 0.5776671  0.13694232 0.38743249]
 [0.54842808 0.00830411 0.62221696 0.3153407 ]
 [0.06475283 0.0668152  0.23010053 0.77594973]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [16]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, size=(4))
c = a * b
print(a)
print(b)
print(c)

[[8 9 9 2]
 [4 6 7 1]
 [1 7 5 8]]
[10  4  2  7]
[[80 36 18 14]
 [40 24 14  7]
 [10 28 10 56]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [18]:
a = np.random.uniform(low=0.0, high=1.0, size=(2, 3))
b = np.random.uniform(low=0.0, high=1.0, size=(3))
c = a * b
print(a)
print(b)
print(c)

[[0.70991841 0.73103311 0.4013502 ]
 [0.86612968 0.72096343 0.17542957]]
[0.38312918 0.33570671 0.32406072]
[[0.27199046 0.24541272 0.13006184]
 [0.33183956 0.24203226 0.05684983]]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [27]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = a * b
print(a)
print(b)
print(c)

[[4 7]
 [3 7]]
[[8 7]
 [6 8]]
[[32 49]
 [18 56]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [26]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
c = np.dot(a, b)
print(a)
print(b)
print(c)

[[ 3  6]
 [10  5]]
[[2 2]
 [7 4]]
[[48 30]
 [55 40]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [25]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
print(a.sum())

[[90 86 90 86 21]
 [29 80 94  9 79]
 [89 90 33 43 80]
 [51  1 42 32  9]
 [75 40 51 61 51]]
1412


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [28]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
c = a - b
print(a)
print(b)
print(c)

[[ 6  2  5 10]
 [ 1  6  9  3]
 [ 5  1  1 10]
 [ 5 10  8  8]]
[[1 5 2 7]
 [9 6 2 4]
 [9 5 2 1]
 [3 9 3 7]]
[[ 5 -3  3  3]
 [-8  0  7 -1]
 [-4 -4 -1  9]
 [ 2  1  5  1]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [44]:
a = np.random.uniform(low= 0.0, high= 1.0, size=(3,3))
b = np.array([sum(a[0, :]),sum(a[1, :]),sum(a[2, :])])
c = b.reshape((3, 1))
print(a)
print(b)
print(c)

[[0.46677067 0.65765126 0.33451671]
 [0.7900004  0.86061814 0.10359695]
 [0.69225225 0.32413196 0.62554044]]
[1.45893865 1.75421549 1.64192464]
[[1.45893865]
 [1.75421549]
 [1.64192464]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [52]:
a = np.random.randint(-11, 11, size=(3, 4))
b = np.square(a)
print(a)
print(b)

[[ 9  2  9  1]
 [ 0 -7  5  7]
 [-4  8 -2  4]]
[[81  4 81  1]
 [ 0 49 25 49]
 [16 64  4 16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [58]:
a = np.random.randint(1, 51, size=(4))
b = np.sqrt(a)
print(a)
print(b)

[16 16  9 20]
[4.         4.         3.         4.47213595]
